name: flutter_media_streamer
description: A Flutter plugin for streaming Media on iOS and Android. Reads Images metadata from the Platform's Gallery as a dart Stream Resizes and gets the images you want or makes Thumbnails
version: 1.0.2
repository: https://github.com/guyo13/flutter_media_streamer
issue_tracker: https://github.com/guyo13/flutter_media_streamer/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  built_value: ^7.1.0
  built_collection: ^4.3.2
  flutter:
    sdk: flutter

dev_dependencies:
  built_value_generator: ^7.1.0
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: net.guyor.flutter_media_streamer
        pluginClass: FlutterMediaStreamerPlugin
      ios:
        pluginClass: FlutterMediaStreamerPlugin

